import AutoPrintOnMount from '@/components/AutoPrintOnMount';
import {
  buildReportContext,
  formatHoursFromMinutes,
  formatMinutesSummary,
  formatTotalWorkHours,
  formatWorkingHours,
  groupTotalMinutes,
  parseFilters,
  type SearchParams,
} from '../_utils/reportData';

import '../print-a4.css';

export default async function ReportsPrintPage({
  searchParams,
}: {
  searchParams?: SearchParams;
}) {
  const filters = parseFilters(searchParams);
  const {
    filteredRows,
    groups,
    autoCount,
    overallMinutes,
    totalRecords,
    totalDisplayedHours,
    totalOvertimeHours,
  } = await buildReportContext(filters);

  const totalWorkHoursText = formatTotalWorkHours(totalDisplayedHours);
  const totalOvertimeHoursText = formatTotalWorkHours(totalOvertimeHours);

  return (
    <main className="report-print mx-auto max-w-5xl space-y-4 p-6">
      <AutoPrintOnMount />
      <header className="space-y-1">
        <h1 className="text-xl font-semibold">個別集計 印刷</h1>
        <p className="text-sm text-gray-600">
          対象: {filters.user || '（未選択）'} / 現場: {filters.site || 'すべて'}
        </p>
        <p className="text-xs text-gray-500">
          年月日: {filters.year ?? '—'}年 {filters.month ?? '—'}月 {filters.day ?? '—'}日 / 自動退勤:
          {filters.auto ?? 'all'}
        </p>
      </header>

      <section className="space-y-2">
        <div className="flex flex-wrap items-center gap-3 text-sm text-gray-800">
          <span>
            合計時間 <strong className="tabular-nums">{formatMinutesSummary(overallMinutes)}</strong>{' '}
            (表示 {totalWorkHoursText})
          </span>
          <span>超過 {totalOvertimeHoursText}</span>
          <span>
            計 <strong className="tabular-nums">{totalRecords}</strong> 件
          </span>
          {autoCount > 0 ? <span>自動退勤 {autoCount} 件</span> : null}
          <span>フィルタ: {filteredRows.length > 0 ? '適用済み' : '—'}</span>
        </div>
      </section>

      {groups.length === 0 ? (
        <p className="text-sm text-gray-600">条件に一致するデータがありません。</p>
      ) : (
        <div className="space-y-4">
          {groups.map((group) => {
            const summaryMinutes = groupTotalMinutes(group);
            const groupWorkingText = formatWorkingHours(group.totalWorkingMinutes);
            const groupOvertimeText = formatHoursFromMinutes(group.totalOvertimeMinutes);
            const groupTotalHoursText = formatHoursFromMinutes(summaryMinutes);
            const groupAutoCount = group.items.filter((item) => item.autoGenerated).length;

            return (
              <section key={group.key} className="space-y-2 rounded border border-gray-200 bg-white p-3">
                <div className="flex flex-wrap items-center gap-3 text-sm font-medium text-gray-800">
                  <span>{group.dateLabel}</span>
                  <span className="tabular-nums">IN: {group.startJst ?? '—'}</span>
                  <span className="tabular-nums">OUT: {group.endJst ?? '—'}</span>
                  <span className="tabular-nums">稼働 {groupWorkingText}</span>
                  <span className="tabular-nums">超過 {groupOvertimeText}</span>
                  <span className="tabular-nums">合計 {groupTotalHoursText}</span>
                  {groupAutoCount > 0 ? (
                    <span className="text-xs text-gray-600">自動退勤 {groupAutoCount} 件</span>
                  ) : null}
                </div>

                <div className="overflow-hidden rounded border border-gray-200">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-3 py-2 text-left">年</th>
                        <th className="px-3 py-2 text-left">月</th>
                        <th className="px-3 py-2 text-left">日</th>
                        <th className="px-3 py-2 text-left">現場名</th>
                        <th className="px-3 py-2 text-left">元請・代理人</th>
                        <th className="px-3 py-2 text-left">始業</th>
                        <th className="px-3 py-2 text-left">終業</th>
                        <th className="px-3 py-2 text-left">稼働</th>
                        <th className="px-3 py-2 text-left">超過</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100 bg-white">
                      {group.items.map((row, index) => (
                        <tr key={`${row.year}-${row.month}-${row.day}-${row.siteName}-${index}`}>
                          <td className="px-3 py-2">{row.year}</td>
                          <td className="px-3 py-2">{row.month}</td>
                          <td className="px-3 py-2">{row.day}</td>
                          <td className="px-3 py-2">{row.siteName}</td>
                          <td className="px-3 py-2">{row.clientName ?? '-'}</td>
                          <td className="px-3 py-2">{row.startJst ?? ''}</td>
                          <td className="px-3 py-2">
                            <div className="flex items-center gap-2">
                              <span>{row.endJst ?? ''}</span>
                              {row.autoGenerated ? <span className="badge-auto inline-block h-3 w-3 rounded-full" /> : null}
                            </div>
                          </td>
                          <td className="px-3 py-2">{formatWorkingHours(row.workingMinutes)}</td>
                          <td className="px-3 py-2">{formatHoursFromMinutes(row.overtimeMinutes)}</td>
                        </tr>
                      ))}
                    </tbody>
                    <tfoot className="bg-gray-50">
                      <tr className="text-sm text-gray-700">
                        <td className="px-3 py-2 font-semibold" colSpan={7}>
                          日計
                        </td>
                        <td className="px-3 py-2">{groupWorkingText}</td>
                        <td className="px-3 py-2">{groupOvertimeText}</td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </section>
            );
          })}
        </div>
      )}
    </main>
  );
}
