import AutoPrintOnMount from '@/components/AutoPrintOnMount';
import {
  buildReportContext,
  formatHoursFromMinutes,
  formatMinutesSummary,
  formatTotalWorkHours,
  formatWorkingHours,
  groupTotalMinutes,
  parseFilters,
  type SearchParams,
} from '../_utils/reportData';

import '../print-a4.css';

export default async function ReportsPrintPage({
  searchParams,
}: {
  searchParams?: SearchParams;
}) {
  const filters = parseFilters(searchParams);
  const {
    groups,
    autoCount,
    overallMinutes,
    totalRecords,
    totalDisplayedHours,
    totalOvertimeHours,
  } = await buildReportContext(filters);

  const totalWorkHoursText = formatTotalWorkHours(totalDisplayedHours);
  const totalOvertimeHoursText = formatTotalWorkHours(totalOvertimeHours);

  const flattenedRows = groups.flatMap((group) => {
    const summaryMinutes = groupTotalMinutes(group);
    const groupWorkingText = formatWorkingHours(group.totalWorkingMinutes);
    const groupOvertimeText = formatHoursFromMinutes(group.totalOvertimeMinutes);
    const groupTotalHoursText = formatHoursFromMinutes(summaryMinutes);

    return group.items.map((row, index) => ({
      row,
      group,
      groupWorkingText,
      groupOvertimeText,
      groupTotalHoursText,
      isFirst: index === 0,
      rowSpan: group.items.length,
    }));
  });

  return (
    <main className="report-print mx-auto w-full max-w-screen-2xl space-y-1 p-1 text-[9px] leading-[1.2]">
      <AutoPrintOnMount />
      <header className="space-y-0.5">
        <h1 className="text-base font-semibold">個別集計 印刷</h1>
        <p className="text-[9px] text-gray-700">
          対象: {filters.user || '（未選択）'} / 現場: {filters.site || 'すべて'} / 年月日: {filters.year ?? '—'}年{' '}
          {filters.month ?? '—'}月 {filters.day ?? '—'}日 / 自動退勤: {filters.auto ?? 'all'}
        </p>
        <p className="text-[9px] text-gray-600">
          合計時間 <strong className="tabular-nums">{formatMinutesSummary(overallMinutes)}</strong> (表示 {totalWorkHoursText}) / 超過{' '}
          {totalOvertimeHoursText} / 計 <strong className="tabular-nums">{totalRecords}</strong> 件 / 自動退勤{' '}
          {autoCount} 件
        </p>
      </header>

      {groups.length === 0 ? (
        <p className="text-sm text-gray-600">条件に一致するデータがありません。</p>
      ) : (
        <div className="overflow-hidden rounded border border-gray-200 bg-white">
          <table className="compact-table ultra-compact w-full text-[9px] leading-[1.15]">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left">日付 / 概要</th>
                <th className="text-left">現場名</th>
                <th className="text-left">元請・代理人</th>
                <th className="text-left">始業</th>
                <th className="text-left">終業</th>
                <th className="text-left">稼働</th>
                <th className="text-left">超過</th>
              </tr>
            </thead>
            <tbody className="bg-white">
              {flattenedRows.map(({ row, group, isFirst, rowSpan, groupWorkingText, groupOvertimeText, groupTotalHoursText }, index) => (
                <tr key={`${row.year}-${row.month}-${row.day}-${row.siteName}-${index}`} className="align-middle">
                  {isFirst ? (
                    <td rowSpan={rowSpan} className="border px-1 py-[2px] align-top leading-tight">
                      <div className="font-semibold">{group.dateLabel}</div>
                      <div className="text-[8px] leading-tight text-gray-600">
                        IN {group.startJst ?? '—'} / OUT {group.endJst ?? '—'}
                        <br />稼働 {groupWorkingText} / 超過 {groupOvertimeText}
                        <br />合計 {groupTotalHoursText}
                      </div>
                    </td>
                  ) : null}
                  <td className="border px-1 py-[2px] text-left">{row.siteName}</td>
                  <td className="border px-1 py-[2px] text-left">{row.clientName ?? '-'}</td>
                  <td className="border px-1 py-[2px] text-left">{row.startJst ?? ''}</td>
                  <td className="border px-1 py-[2px] text-left">
                    <div className="flex items-center gap-1">
                      <span>{row.endJst ?? ''}</span>
                      {row.autoGenerated ? <span className="badge-auto inline-block h-2.5 w-2.5 rounded-full" /> : null}
                    </div>
                  </td>
                  <td className="border px-1 py-[2px] text-right tabular-nums">{formatWorkingHours(row.workingMinutes)}</td>
                  <td className="border px-1 py-[2px] text-right tabular-nums">{formatHoursFromMinutes(row.overtimeMinutes)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </main>
  );
}
