'use client';
import React from 'react';
import type { SessionRecord } from '@/app/(protected)/reports/_lib/groupByUserDate';

export default function SessionBreakdown({ sessions }: { sessions: SessionRecord[] }) {
  if (!sessions?.length) return null;
  return (
    <details className="mt-2 print:hidden">
      <summary className="cursor-pointer text-sm text-neutral-500">内訳（セッション明細）</summary>
      <div className="mt-2 overflow-auto border rounded">
        <table className="min-w-[640px] w-full text-sm">
          <thead className="bg-neutral-50">
            <tr className="text-left">
              <th className="px-2 py-1">開始</th>
              <th className="px-2 py-1">終了</th>
              <th className="px-2 py-1">分</th>
              <th className="px-2 py-1">機械</th>
              <th className="px-2 py-1">業務内容</th>
              <th className="px-2 py-1">自動</th>
              <th className="px-2 py-1">現場</th>
            </tr>
          </thead>
          <tbody>
            {sessions.map((s, i) => (
              <tr key={i} className="border-t">
                <td className="px-2 py-1 whitespace-nowrap">{s.start ?? ''}</td>
                <td className="px-2 py-1 whitespace-nowrap">{s.end ?? ''}</td>
                <td className="px-2 py-1">{Number(s.durationMin ?? 0)}</td>
                <td className="px-2 py-1">
                  {s.machineId ?? ''}
                  {s.machineName ? `（${s.machineName}）` : ''}
                </td>
                <td className="px-2 py-1">{s.workDescription ?? ''}</td>
                <td className="px-2 py-1">{s.autoGenerated ? 'AUTO OUT' : ''}</td>
                <td className="px-2 py-1">{s.siteName ?? ''}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </details>
  );
}
