import Link from 'next/link';

import ReportsTabs from '@/components/reports/ReportsTabs';
import { usersTable } from '@/lib/airtable';
import PrintA4Button from '@/components/PrintA4Button';
import { groupByUserDate, type ReportLog } from '@/lib/report-groupers';
import { formatMinutes, fmtDate, fmtTime } from '@/lib/format';
import { fetchSessionReportRows, type SessionReportRow } from '@/src/lib/sessions-reports';

import './print-a4.css';

type SearchParams = Record<string, string | string[] | undefined>;

type AutoFilter = 'all' | 'only' | 'exclude';

type Filters = {
  user: string;
  site: string;
  year?: number;
  month?: number;
  day?: number;
  auto?: AutoFilter;
};

async function fetchUsers(): Promise<string[]> {
  const records = await usersTable
    .select({ fields: ['name'], sort: [{ field: 'name', direction: 'asc' }] })
    .all();
  const names = new Set<string>();
  for (const record of records) {
    const name = typeof record.fields.name === 'string' ? record.fields.name : null;
    if (name) {
      names.add(name);
    }
  }
  return Array.from(names).sort((a, b) => a.localeCompare(b, 'ja'));
}

function toSingleValue(value: string | string[] | undefined): string {
  if (Array.isArray(value)) {
    return value[0] ?? '';
  }
  return value ?? '';
}

function toNumberValue(value: string | string[] | undefined): number | undefined {
  const single = toSingleValue(value).trim();
  if (!single) return undefined;
  const parsed = Number.parseInt(single, 10);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function toAutoFilter(value: string): AutoFilter | undefined {
  if (value === 'only' || value === 'exclude') {
    return value;
  }
  return undefined;
}

function toReportLog(session: SessionReportRow): ReportLog {
  const userIdCandidate =
    session.userRecordId ??
    (session.userId != null ? String(session.userId) : session.userName ?? session.id);
  const userId = userIdCandidate || session.id;
  const machineId = typeof session.machineId === 'string' ? session.machineId.trim() : '';
  const machineName = typeof session.machineName === 'string' ? session.machineName.trim() : '';
  const machine = machineId || machineName ? { machineId, machineName } : null;

  return {
    id: session.id,
    userId,
    userName: session.userName,
    startAt: session.start,
    endAt: session.end,
    date: session.date,
    siteId: session.siteRecordId,
    siteName: session.siteName,
    machine,
    workType: session.workDescription,
    durationMinutes: session.durationMin,
  } satisfies ReportLog;
}

function formatMachine(log: ReportLog): { text: string; title?: string } {
  const rawId = log.machine?.machineId ?? null;
  const rawName = log.machine?.machineName ?? null;
  const idText = typeof rawId === 'string' ? rawId.trim() : '';
  const nameText = typeof rawName === 'string' ? rawName.trim() : '';
  if (!idText && !nameText) {
    return { text: '—' };
  }
  if (idText && nameText) {
    const combined = `${idText} | ${nameText}`;
    return { text: combined, title: combined };
  }
  const text = nameText || idText;
  return { text, title: text };
}

export default async function ReportsPage({ searchParams }: { searchParams?: SearchParams }) {
  const params = searchParams ?? {};
  const filters: Filters = {
    user: toSingleValue(params.user).trim(),
    site: toSingleValue(params.site).trim(),
    year: toNumberValue(params.year),
    month: toNumberValue(params.month),
    day: toNumberValue(params.day),
    auto: toAutoFilter(toSingleValue(params.auto).trim()),
  };

  const users = await fetchUsers();
  const sessionsRaw: SessionReportRow[] = filters.user
    ? await fetchSessionReportRows({ userName: filters.user })
    : [];

  const availableYears = Array.from(
    new Set(
      sessionsRaw
        .map((session) => session.year)
        .filter((value): value is number => Number.isInteger(value)),
    ),
  ).sort((a, b) => a - b);

  const availableMonths = Array.from(
    new Set(
      sessionsRaw
        .map((session) => session.month)
        .filter((value): value is number => Number.isInteger(value)),
    ),
  ).sort((a, b) => a - b);

  const availableDays = Array.from(
    new Set(
      sessionsRaw
        .map((session) => session.day)
        .filter((value): value is number => Number.isInteger(value)),
    ),
  ).sort((a, b) => a - b);

  const availableSites = Array.from(
    new Set(
      sessionsRaw
        .map((session) => (typeof session.siteName === 'string' ? session.siteName.trim() : ''))
        .filter((name): name is string => Boolean(name)),
    ),
  ).sort((a, b) => a.localeCompare(b, 'ja'));

  const filteredSessions = sessionsRaw.filter((session) => {
    if (!session.isCompleted) return false;
    if (!session.date) return false;
    if (filters.auto === 'only' && !session.autoGenerated) return false;
    if (filters.auto === 'exclude' && session.autoGenerated) return false;
    if (filters.year && session.year !== filters.year) return false;
    if (filters.month && session.month !== filters.month) return false;
    if (filters.day && session.day !== filters.day) return false;
    const siteName = typeof session.siteName === 'string' ? session.siteName.trim() : '';
    if (filters.site && siteName !== filters.site) return false;
    return true;
  });

  const reportLogs = filteredSessions.map(toReportLog);
  const groups = groupByUserDate(reportLogs);
  const totalMinutes = groups.reduce((sum, group) => sum + group.totalMinutes, 0);
  const totalRecords = groups.reduce((sum, group) => sum + group.count, 0);
  const autoCount = filteredSessions.filter((session) => session.autoGenerated).length;

  return (
    <main className="mx-auto max-w-5xl space-y-6 p-6">
      <ReportsTabs />
      <div className="report-print space-y-6">
        <header className="space-y-2">
          <h1 className="text-2xl font-semibold text-gray-900">個別集計</h1>
          <p className="text-sm text-gray-600">従業員ごとの IN/OUT ペアリングから稼働時間を算出します。</p>
        </header>

        <div className="_print-toolbar _print-hidden">
          <PrintA4Button />
        </div>

        <form className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6" method="get">
          <div className="flex flex-col">
            <label htmlFor="user" className="text-sm font-medium text-gray-700">
              従業員名
            </label>
            <select
              id="user"
              name="user"
              defaultValue={filters.user}
              className="mt-1 min-w-[200px] rounded border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
              aria-describedby="user-helper"
            >
              <option value="">-- 選択してください --</option>
              {users.map((name) => (
                <option key={name} value={name}>
                  {name}
                </option>
              ))}
            </select>
            <span id="user-helper" className="mt-1 text-xs text-gray-500">
              対象の従業員を選ぶとグリッドが表示されます。
            </span>
          </div>

          <div className="flex flex-col">
            <label htmlFor="site" className="text-sm font-medium text-gray-700">
              現場名
            </label>
            <select
              id="site"
              name="site"
              defaultValue={filters.site}
              disabled={!filters.user}
              className="mt-1 rounded border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 disabled:cursor-not-allowed disabled:bg-gray-100"
            >
              <option value="">-- すべて --</option>
              {availableSites.map((site) => (
                <option key={site} value={site}>
                  {site}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col">
            <label htmlFor="year" className="text-sm font-medium text-gray-700">
              年
            </label>
            <select
              id="year"
              name="year"
              defaultValue={filters.year?.toString() ?? ''}
              disabled={!filters.user}
              className="mt-1 rounded border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 disabled:cursor-not-allowed disabled:bg-gray-100"
            >
              <option value="">-- すべて --</option>
              {availableYears.map((year) => (
                <option key={year} value={year}>
                  {year}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col">
            <label htmlFor="month" className="text-sm font-medium text-gray-700">
              月
            </label>
            <select
              id="month"
              name="month"
              defaultValue={filters.month?.toString() ?? ''}
              disabled={!filters.user}
              className="mt-1 rounded border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 disabled:cursor-not-allowed disabled:bg-gray-100"
            >
              <option value="">-- すべて --</option>
              {availableMonths.map((month) => (
                <option key={month} value={month}>
                  {month}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col">
            <label htmlFor="day" className="text-sm font-medium text-gray-700">
              日
            </label>
            <select
              id="day"
              name="day"
              defaultValue={filters.day?.toString() ?? ''}
              disabled={!filters.user}
              className="mt-1 rounded border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 disabled:cursor-not-allowed disabled:bg-gray-100"
            >
              <option value="">-- すべて --</option>
              {availableDays.map((day) => (
                <option key={day} value={day}>
                  {day}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col">
            <label htmlFor="auto" className="text-sm font-medium text-gray-700">
              自動退勤
            </label>
            <select
              id="auto"
              name="auto"
              defaultValue={filters.auto ?? 'all'}
              disabled={!filters.user}
              className="mt-1 rounded border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 disabled:cursor-not-allowed disabled:bg-gray-100"
            >
              <option value="all">すべて</option>
              <option value="only">自動のみ</option>
              <option value="exclude">自動を除外</option>
            </select>
          </div>

          <div className="flex items-end gap-2">
            <button
              type="submit"
              className="inline-flex w-full items-center justify-center rounded border border-indigo-500 bg-indigo-500 px-4 py-2 text-sm font-medium text-white transition hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
            >
              絞り込み
            </button>
          </div>
        </form>

        <div className="flex items-center justify-between text-xs text-gray-500 _print-hidden">
          <span>※ サマリーは日付×従業員で折りたたみ表示されます。必要に応じて上部のフィルターをご利用ください。</span>
          <Link href="/reports" className="text-indigo-600 underline">
            条件をクリア
          </Link>
        </div>

        {filters.user && (
          <section className="space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-2 rounded-md bg-gray-50 px-4 py-3 text-sm text-gray-700">
              <span>
                合計時間: <strong className="tabular-nums">{formatMinutes(totalMinutes)}</strong> / 計{' '}
                <strong className="tabular-nums">{totalRecords}</strong>件
              </span>
              {autoCount > 0 ? (
                <span className="text-xs text-gray-500">自動退勤 {autoCount} 件を含みます</span>
              ) : null}
            </div>

            {groups.length === 0 ? (
              <div className="rounded border border-dashed border-gray-300 bg-white px-6 py-12 text-center text-sm text-gray-500">
                条件に一致するデータがありません。
              </div>
            ) : (
              <div className="space-y-3">
                {groups.map((group) => {
                  return (
                    <details key={group.key} className="rounded border bg-white">
                      <summary className="flex cursor-pointer items-center gap-4 px-4 py-3">
                        <span className="w-32 text-sm font-medium text-gray-900">{fmtDate(group.date)}</span>
                        <span className="flex-1 truncate text-sm text-gray-700">{group.userName ?? group.userId}</span>
                        <span className="w-28 text-right text-sm font-semibold text-gray-900 tabular-nums">
                          {formatMinutes(group.totalMinutes)}
                        </span>
                        <span className="w-20 text-right text-sm text-gray-600 tabular-nums">{group.count}件</span>
                      </summary>
                      <div className="border-t px-4 py-3">
                        <table className="w-full table-auto text-sm">
                          <thead>
                            <tr className="text-left text-xs uppercase tracking-wide text-gray-500">
                              <th className="pb-2">開始</th>
                              <th className="pb-2">終了</th>
                              <th className="pb-2">サイト</th>
                              <th className="pb-2">機械</th>
                              <th className="pb-2">作業</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-gray-200 text-gray-900">
                            {group.items.map((item) => {
                              const machine = formatMachine(item);
                              return (
                                <tr key={item.id}>
                                  <td className="py-2 pr-4 tabular-nums">{fmtTime(item.startAt)}</td>
                                  <td className="py-2 pr-4 tabular-nums">{fmtTime(item.endAt)}</td>
                                  <td className="py-2 pr-4">{item.siteName ?? item.siteId ?? '—'}</td>
                                  <td className="py-2 pr-4">
                                    <span title={machine.title}>{machine.text}</span>
                                  </td>
                                  <td className="py-2">{item.workType ?? '—'}</td>
                                </tr>
                              );
                            })}
                          </tbody>
                        </table>
                      </div>
                    </details>
                  );
                })}
              </div>
            )}
          </section>
        )}
      </div>
    </main>
  );
}
