export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import ExcelJS from 'exceljs';
import { NextRequest, NextResponse } from 'next/server';

import { auth } from '@/lib/auth';
import {
  buildReportContext,
  flattenReportGroups,
  formatHoursFromMinutes,
  formatWorkingHours,
  parseFilters,
  sortReportItems,
  summarizeReportItems,
  type SearchParams,
} from '@/app/reports/_utils/reportData';

function buildFiltersFromSearchParams(searchParams: URLSearchParams) {
  const params: SearchParams = {
    user: searchParams.get('user') ?? '',
    site: searchParams.get('site') ?? '',
    year: searchParams.get('year') ?? undefined,
    month: searchParams.get('month') ?? undefined,
    day: searchParams.get('day') ?? undefined,
    auto: searchParams.get('auto') ?? '',
  };
  const filters = parseFilters(params);
  if (!filters.auto && (params.auto ?? '').toString().trim() === 'all') {
    filters.auto = undefined;
  }
  return filters;
}

function buildDateLabel(filters: {
  year?: number;
  month?: number;
  day?: number;
}) {
  if (filters.year && filters.month && filters.day) {
    return `${filters.year}${String(filters.month).padStart(2, '0')}${String(filters.day).padStart(2, '0')}`;
  }
  if (filters.year && filters.month) {
    return `${filters.year}${String(filters.month).padStart(2, '0')}`;
  }
  if (filters.year) {
    return `${filters.year}`;
  }
  return 'all';
}

export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: 'UNAUTHORIZED' }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const filters = buildFiltersFromSearchParams(searchParams);
  if (!filters.user) {
    return NextResponse.json({ error: 'user is required' }, { status: 400 });
  }

  const context = await buildReportContext(filters);
  const flatItems = flattenReportGroups(context.groups);
  const sortedItems = sortReportItems(flatItems);
  const { totalWorkingMinutes, totalOvertimeMinutes, totalSummaryMinutes } =
    summarizeReportItems(flatItems);

  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('user-report');

  sheet.addRow(['年', '月', '日', '曜', '従業員', '始業', '終業', '稼働', '超過', '計']);
  sheet.getRow(1).font = { bold: true };

  sortedItems.forEach((row) => {
    const totalMinutes = row.workingMinutes + row.overtimeMinutes;
    const weekdayLabel = new Date(
      row.year,
      Math.max(0, row.month - 1),
      row.day,
    ).toLocaleDateString('ja-JP', { weekday: 'short' });
    const endLabel = row.autoGenerated ? `${row.endJst ?? '—'} (AUTO)` : row.endJst ?? '—';

    sheet.addRow([
      row.year,
      row.month,
      row.day,
      weekdayLabel,
      filters.user,
      row.startJst ?? '—',
      endLabel,
      formatWorkingHours(row.workingMinutes),
      formatHoursFromMinutes(row.overtimeMinutes),
      formatHoursFromMinutes(totalMinutes),
    ]);
  });

  const totalRow = sheet.addRow([
    '合計',
    '',
    '',
    '',
    '',
    '',
    '',
    formatWorkingHours(totalWorkingMinutes),
    formatHoursFromMinutes(totalOvertimeMinutes),
    formatHoursFromMinutes(totalSummaryMinutes),
  ]);
  totalRow.font = { bold: true };

  const out = await workbook.xlsx.writeBuffer();
  const buffer = Buffer.isBuffer(out) ? out : Buffer.from(out as ArrayBuffer);
  if (!(buffer[0] === 0x50 && buffer[1] === 0x4b)) {
    throw new Error('XLSX buffer is not ZIP(PK). exceljs shim might be used.');
  }

  const dateLabel = buildDateLabel(filters);
  const filename = `user-report_${dateLabel}_${filters.user}.xlsx`;

  return new Response(buffer, {
    status: 200,
    headers: {
      'Content-Type':
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`,
      'Cache-Control': 'no-store',
    },
  });
}
